課題3
KakizakiHayate/qtl_list_data pull request #2
Opened 2023-04-24 23:16 UTC by KakizakiHayate

## issue

- Close #1 

## Overview
リストデータを作成し、List表示した。

## Screenshots
![Simulator Screen Shot - iPhone 14 Pro - 2023-04-25 at 08 08 49](https://user-images.githubusercontent.com/109132975/234135535-34af2fe0-94b1-4321-b688-6d80378e28e5.png)

## Checklist
- [x] Format code with SwiftLint (⌘ + B)
- [x] Close #1

2023-04-25 06:32 UTC, mht-naoki-muramoto requested changes
確認お願いします！

2023-04-25 06:32 UTC, mht-naoki-muramoto commented on ListData/ListView.swift
> +
[must] Modelはファイル分けした方が良い

2023-04-25 06:32 UTC, mht-naoki-muramoto commented on ListData/ListView.swift
> +    ]
[nits] Constファイルに持たせた方が良いかも

2023-04-28 05:32 UTC, KakizakiHayate commented on ListData/ListView.swift
> +
ConstFileを作成するにあたって、このModelは削除しました。

2023-04-28 05:34 UTC, KakizakiHayate commented on ListData/ListView.swift
> +    ]
ConstFileに記述しました！
↑ ab3c9814c82c3b1e3fb8823e6fa0c6731daf373d
 
そしてListで表示しました！
↑ 3439eb51a965490ccf03def99614dcfb8e19ee9f

2023-04-28 05:43 UTC, mht-naoki-muramoto approved these changes
LGTM!

2023-11-21 07:35 UTC, merged